CDK stacks for lambda and pipeline
ndlib/lambda_auth_blueprints pull request #1
Opened 2021-02-05 16:00 UTC by mlkirkpatrick

2021-02-05 18:10 UTC, rdoughty approved these changes

2021-02-05 21:17 UTC, jgondron requested changes

2021-02-05 21:17 UTC, jgondron commented on lib/lambda-auth-pipeline-stack.ts
> +      actions: [deployToTestAction, manualApprovalAction],
Do you have a reliable way to test this? If this is a piece of shared infrastructure that lots of other APIs use, you'll really want to be sure new deploys work

2021-02-05 21:17 UTC, jgondron commented on lib/lambda-auth-stack.ts
> +      functionName: props.stackName,
Are you sure you want to name this? Would probably be better to let cloudformation name it, then export it as something like `stackname:LambdaName` so that other things can import that. An export/import binding is probably a good thing here to prevent breaking downstream APIs that use this.

2021-02-05 21:19 UTC, mlkirkpatrick commented on lib/lambda-auth-stack.ts
> +      functionName: props.stackName,
Maybe, but everything else already looks for this specifically by name. If I don't name it the same thing then we'll have to update all of the other stacks.

2021-02-05 21:25 UTC, mlkirkpatrick commented on lib/lambda-auth-pipeline-stack.ts
> +      actions: [deployToTestAction, manualApprovalAction],
Well since it is just a lambda the only thing we can do directly is to invoke the lambda, and we'll have to pass in a valid Okta token if we want to make sure it actually works and doesn't just return unauthorized for everyone.

We could set up an Okta app and use the client_credentials workflow to generate a token during the pipeline... Of course, there are code paths that depend on a more "normal" token with a netid, so it would still be an imperfect test. It is a valid concern though, and maybe that's what we should do regardless.

2021-02-08 14:56 UTC, mlkirkpatrick commented on lib/lambda-auth-stack.ts
> +      functionName: props.stackName,
I added an export so we can use imports in stacks in the future if desired. I'm keeping the explicit function name though for backwards compatibility.

2021-02-08 15:34 UTC, jgondron approved these changes

2021-02-08 19:41 UTC, merged